### ISSUE TITLE
Adress Bar

### ISSUE THREAD

**Issue by max1c** [rtws/custom-homepage#1]
Adress bar is not cleared/selected in Opera 29. Could you add a "ctrl+e" shortcut to be auto executed after new tab is opened to illiminate this problem?

**Comment by rtws** [comment]
From pure Javascript extension: unfortunately not. I spent a lot of time to achieve this without any success.

From an extension with native messaging host: yes, but it requires you to install a separate software. TBD in 1-2 weeks.

**Comment by max1c** [comment]
I see, that's unfortunate. I still can't believe Opera devs can't give us an option to have bookmarks as a default new tab. Anyway, thanks for the reply and thanks for the extension it's very useful.

**Comment by rtws** [comment]
The solution is "simple":
1. an application (native messaging host) which sends F8 keypress event to activate Opera window
2. an installer for the application
3. an update for the extension to call this application to send the keypress event
4. it will be Windows-only initially, Linux support may come later (and maybe never)

Workaround rulez :)
